// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: turtagent.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptRequest) Reset() {
	*x = PromptRequest{}
	mi := &file_turtagent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptRequest) ProtoMessage() {}

func (x *PromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_turtagent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptRequest.ProtoReflect.Descriptor instead.
func (*PromptRequest) Descriptor() ([]byte, []int) {
	return file_turtagent_proto_rawDescGZIP(), []int{0}
}

func (x *PromptRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type PromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TextChunk     string                 `protobuf:"bytes,1,opt,name=text_chunk,json=textChunk,proto3" json:"text_chunk,omitempty"`
	IsThinking    bool                   `protobuf:"varint,2,opt,name=is_thinking,json=isThinking,proto3" json:"is_thinking,omitempty"`
	IsFinal       bool                   `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptResponse) Reset() {
	*x = PromptResponse{}
	mi := &file_turtagent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptResponse) ProtoMessage() {}

func (x *PromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_turtagent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptResponse.ProtoReflect.Descriptor instead.
func (*PromptResponse) Descriptor() ([]byte, []int) {
	return file_turtagent_proto_rawDescGZIP(), []int{1}
}

func (x *PromptResponse) GetTextChunk() string {
	if x != nil {
		return x.TextChunk
	}
	return ""
}

func (x *PromptResponse) GetIsThinking() bool {
	if x != nil {
		return x.IsThinking
	}
	return false
}

func (x *PromptResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

var File_turtagent_proto protoreflect.FileDescriptor

const file_turtagent_proto_rawDesc = "" +
	"\n" +
	"\x0fturtagent.proto\x12\tturtagent\"'\n" +
	"\rPromptRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"k\n" +
	"\x0ePromptResponse\x12\x1d\n" +
	"\n" +
	"text_chunk\x18\x01 \x01(\tR\ttextChunk\x12\x1f\n" +
	"\vis_thinking\x18\x02 \x01(\bR\n" +
	"isThinking\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal2c\n" +
	"\x16TurtAgentStreamService\x12I\n" +
	"\x10GenerateResponse\x12\x18.turtagent.PromptRequest\x1a\x19.turtagent.PromptResponse0\x01B\fZ\n" +
	"./protobufb\x06proto3"

var (
	file_turtagent_proto_rawDescOnce sync.Once
	file_turtagent_proto_rawDescData []byte
)

func file_turtagent_proto_rawDescGZIP() []byte {
	file_turtagent_proto_rawDescOnce.Do(func() {
		file_turtagent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_turtagent_proto_rawDesc), len(file_turtagent_proto_rawDesc)))
	})
	return file_turtagent_proto_rawDescData
}

var file_turtagent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_turtagent_proto_goTypes = []any{
	(*PromptRequest)(nil),  // 0: turtagent.PromptRequest
	(*PromptResponse)(nil), // 1: turtagent.PromptResponse
}
var file_turtagent_proto_depIdxs = []int32{
	0, // 0: turtagent.TurtAgentStreamService.GenerateResponse:input_type -> turtagent.PromptRequest
	1, // 1: turtagent.TurtAgentStreamService.GenerateResponse:output_type -> turtagent.PromptResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_turtagent_proto_init() }
func file_turtagent_proto_init() {
	if File_turtagent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turtagent_proto_rawDesc), len(file_turtagent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_turtagent_proto_goTypes,
		DependencyIndexes: file_turtagent_proto_depIdxs,
		MessageInfos:      file_turtagent_proto_msgTypes,
	}.Build()
	File_turtagent_proto = out.File
	file_turtagent_proto_goTypes = nil
	file_turtagent_proto_depIdxs = nil
}
