// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: turtagent.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TurtAgentStreamService_GenerateResponse_FullMethodName = "/turtagent.TurtAgentStreamService/GenerateResponse"
)

// TurtAgentStreamServiceClient is the client API for TurtAgentStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TurtAgentStreamServiceClient interface {
	GenerateResponse(ctx context.Context, in *PromptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PromptResponse], error)
}

type turtAgentStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTurtAgentStreamServiceClient(cc grpc.ClientConnInterface) TurtAgentStreamServiceClient {
	return &turtAgentStreamServiceClient{cc}
}

func (c *turtAgentStreamServiceClient) GenerateResponse(ctx context.Context, in *PromptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PromptResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TurtAgentStreamService_ServiceDesc.Streams[0], TurtAgentStreamService_GenerateResponse_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PromptRequest, PromptResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TurtAgentStreamService_GenerateResponseClient = grpc.ServerStreamingClient[PromptResponse]

// TurtAgentStreamServiceServer is the server API for TurtAgentStreamService service.
// All implementations must embed UnimplementedTurtAgentStreamServiceServer
// for forward compatibility.
type TurtAgentStreamServiceServer interface {
	GenerateResponse(*PromptRequest, grpc.ServerStreamingServer[PromptResponse]) error
	mustEmbedUnimplementedTurtAgentStreamServiceServer()
}

// UnimplementedTurtAgentStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTurtAgentStreamServiceServer struct{}

func (UnimplementedTurtAgentStreamServiceServer) GenerateResponse(*PromptRequest, grpc.ServerStreamingServer[PromptResponse]) error {
	return status.Error(codes.Unimplemented, "method GenerateResponse not implemented")
}
func (UnimplementedTurtAgentStreamServiceServer) mustEmbedUnimplementedTurtAgentStreamServiceServer() {
}
func (UnimplementedTurtAgentStreamServiceServer) testEmbeddedByValue() {}

// UnsafeTurtAgentStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TurtAgentStreamServiceServer will
// result in compilation errors.
type UnsafeTurtAgentStreamServiceServer interface {
	mustEmbedUnimplementedTurtAgentStreamServiceServer()
}

func RegisterTurtAgentStreamServiceServer(s grpc.ServiceRegistrar, srv TurtAgentStreamServiceServer) {
	// If the following call panics, it indicates UnimplementedTurtAgentStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TurtAgentStreamService_ServiceDesc, srv)
}

func _TurtAgentStreamService_GenerateResponse_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PromptRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TurtAgentStreamServiceServer).GenerateResponse(m, &grpc.GenericServerStream[PromptRequest, PromptResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TurtAgentStreamService_GenerateResponseServer = grpc.ServerStreamingServer[PromptResponse]

// TurtAgentStreamService_ServiceDesc is the grpc.ServiceDesc for TurtAgentStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TurtAgentStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "turtagent.TurtAgentStreamService",
	HandlerType: (*TurtAgentStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenerateResponse",
			Handler:       _TurtAgentStreamService_GenerateResponse_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "turtagent.proto",
}
